Concurrent gcp aws stage
bf2fc6cc711aee1a0c2a/e2e-test-suite pull request #456
Opened 2023-01-31 09:40 UTC by tonyxrmdavidson

Update to rename Kafka Instances, Service Accounts and Service Registry using the CLOUD_PROVIDER environment variable. This is needed to distinguish between aws staging names and gcp staging names and will avoid errors when running concurrent E2E test runs.

2023-01-31 10:48 UTC, henryZrncik requested changes
just few changes: 
firstly forgotten class (e.g. new class QuotaTest), althoguh this class will actually need more diligent treatment. 

secondly: service registries: currently 1 instnace so running this will be blocked untiil resolved. 

thirdly: there are also other resources beside those which had launch key, mainly resources on user OSD, so there are lot of resources in quickstarts which will clash unless you add it there.

2023-01-31 10:48 UTC, henryZrncik commented on src/test/java/io/managed/services/test/registry/RegistryKafkaIntegrationTest.java
currently only place for 1 service regisstry instance, one test will fail at the moment.

2023-01-31 10:56 UTC, agullon commented
Hi @tonyxrmdavidson , I think https://github.com/bf2fc6cc711aee1a0c2a/e2e-test-suite/blob/concurrentGcpAwsStage/src/test/java/io/managed/services/test/kafka/KafkaOverseeingTest.java is missing, can you take a look at it? thanks

2023-01-31 11:58 UTC, tonyxrmdavidson commented
Do Not Merge WIP

2023-02-01 10:04 UTC, henryZrncik requested changes
suffixes works for me, 

what is worth considering now is the fact that in two commits you are keeping log information for stage dev users, in a file that is not even in the final version. So I would suggest squash of these commits into the 1. 

also considering the name, of these PR, it suggests that AWS, GCP can run next to each other, for that you need to do more changes in code base (mainly modify quota Class), and also parametrize endpoints in billing metrics class (currently we are targeting data plane for aws). 

So we can either push this but renaming it to something more suitable, or address also points mentioned above.

2023-02-01 10:11 UTC, henryZrncik commented
Anyway, if you want to proceed with running it next to each other, least painful solution right now would be to create suite which would omit  quota tests, billing metric tests, for gcp. (and resolve this on their own, but these are not so drastic changes anyway). 
if so, aws suites continues to test all classes as it is doing at this moment.

2023-02-01 11:09 UTC, henryZrncik approved these changes
with these changes works for me.

2023-02-01 11:26 UTC, kornys approved these changes

2023-02-01 11:37 UTC, merged